- defaults:
    link:
      relink: true
    shell:
      stdout: true
      stderr: true

- clean: ['~']

- link:
    ~/.Brewfile: mac/Brewfile
    ~/.chunkwmrc: mac/chunkwmrc
    ~/.skhdrc: mac/skhdrc
    ~/Library/Application Support/Übersicht/widgets/Pecan: mac/Pecan
    ~/Library/Application Support/Übersicht/widgets/Xanthia: mac/Xanthia

- shell:
  - [brew bundle cleanup --file=$HOME/.Brewfile --force, Uninstall all deps not in Brewfile]
  - [brew bundle install --file=$HOME/.Brewfile, Install or upgrade all deps not in Brewfile]
  - [brew services restart crisidev/chunkwm/chunkwm, Launchd restart chunkwm]
  - [brew services restart koekeishiya/formulae/skhd, Launchd restart skhd]
